version: "3.9"

services:
  painel-supermercado:
    container_name: painel-supermercado
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8221:3000"
    environment:
      NODE_ENV: production
      TZ: America/Sao_Paulo
      RHID_API_BASE_URL: https://www.rhid.com.br/v2/api.svc
      RHID_API_TOKEN: ${RHID_API_TOKEN}
      RHID_FETCH_APURACAO: "false"
